---
title: "RIVM COVID-19 Data"
author: "Joeri Jongbloets"
date: "`r strftime(Sys.Date(), '%B %d %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning=FALSE
  
)

library("EpiEstim")
library("tidyverse")
```

```{r load_data, include=FALSE}
# Load project settings
source(here::here("settings.R"))

# load helper functions
source(file.path(lib.dir, "trim.R"))
source(file.path(lib.dir, "estimate_r.R"))

# load data
source(file.path(data.dir, "rivm.R"))

df.rivm <- load_rivm()

si_mean <- 5
si_sd <- 3.4

```

* Last timepoint: `r df.rivm %>% pull(date_reported) %>% max()`

```{r}
f_plot_increase <- function(d) {
  d %>%
    filter( value > 0 ) %>%
    ggplot(aes(x = date_reported, y= value, colour= metric )) +
    facet_wrap(~metric, scales="free_y") +
    geom_smooth(se=F, method = "loess", formula = y ~ x) +
    geom_point() +
    scale_y_log10() +
    labs(
      x = "Date", y = "new #"
    )
}

f_plot_cumulative <- function(d, show.log = TRUE) {
  p <- d %>%
    group_by(metric) %>%
    arrange(date_reported) %>%
    mutate(
      cum_value = cumsum(value)
    ) %>%
    filter( cum_value > 0 ) %>%
    ggplot(aes(x = date_reported, y= cum_value, colour= metric )) +
    facet_wrap(~metric, scales="free_y") +
    geom_smooth(se=F, method = "loess", formula = y ~ x) +
    geom_point() +
    labs(
      x = "Date", y = "cumalative #"
    )
  
  if (show.log) {
    p <- p + scale_y_log10()
  }
  
  p
}

f_plot_r_over_time <- function( d ) {
  
  d %>%
    ggplot(aes(x=date_reported, y=r_mean )) +
    geom_point(aes(colour = metric)) +
    geom_line(aes(colour = metric)) +
    geom_ribbon(aes(ymin = r_ci_lower, ymax = r_ci_upper, fill = metric), alpha=0.1) +
    geom_hline(aes(yintercept = 1), colour="red") +
    expand_limits(y=0) +
    labs(
      x = "Date",
      y = "Estimated R"
    )
  
}

f_plot_r_over_incidence <- function( d ) {
  
  d %>%
    group_by(metric) %>%
    arrange(date_reported) %>%
    mutate(
      cum_value = cumsum(value)
    ) %>%
    filter( cum_value > 0 ) %>%
    ggplot(aes(x=cum_value, y=r_mean, colour=metric )) +
    facet_wrap(~metric, scales="free_x") +
    geom_point() +
    geom_line() +
    expand_limits(y=0) +
    labs(
      x = "# cases",
      y = "Estimated R"
    )
}

```

## Cases per Day

```{r}
df.rivm %>%
  f_plot_increase() +
  theme(legend.position = "bottom")
```

```{r}
df.rivm %>%
  f_plot_cumulative(show.log = F) +
  theme(legend.position = "bottom")
```

```{r}
df.rivm %>%
  f_plot_cumulative() +
  theme(legend.position = "bottom")
```

## Death Rate

```{r}
f_plot_death_rate <- function( .d ) {
  
  .d %>%
    pivot_wider(
      names_from = metric,
      names_prefix = "new_",
      values_from = value
    ) %>%
    arrange(date_reported) %>%
    mutate(
      cum_cases = cumsum(new_cases),
      cum_deaths = cumsum(new_deaths),
      death_rate = cum_deaths / cum_cases
    ) %>%
    filter(cum_cases > 0, cum_deaths > 0) %>%
    ggplot(aes(x=date_reported, y=death_rate)) +
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = scales::percent) +
    labs(
      x = "Date",
      y = "Death Rate"
    )
  
}
```

### Dutch Situation

```{r}
df.rivm %>%
  f_plot_death_rate()
```

## Estimate R

```{r}
df.r <- df.rivm %>%
  group_by(geo_id, metric) %>%
  nest() %>%
  group_by(geo_id, metric) %>%
  mutate(
    model = map(data, f_estimate_r, cases_from = value, si_mean = si_mean, si_sd = si_sd),
    r_estimate = map2(data, model, f_extract_r, time_from = date_reported)
  ) %>%
  unnest(r_estimate)
```

```{r}
df.r %>%
  f_plot_r_over_time
```

```{r}
df.r %>%
  f_plot_r_over_incidence
```