---
title: "ECDC COVID-19 Data"
author: "Joeri Jongbloets"
date: "`r strftime(Sys.Date(), '%B %d %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning=FALSE
  
)

library("EpiEstim")
library("tidyverse")
```

```{r load_data, include=FALSE}
# Load project settings
source(here::here("settings.R"))

# load data
source(file.path(data.dir, "ecdc.R"))

df.ecdc <- load_ecdc()

european <- c(
  "NL", "DE", "PL",
  "BE", "LU",
  "FR", 
  "ES", "IT", "EL",
  "NO", "SE", "FI", 
  "UK"
)

si_mean <- 5
si_sd <- 3.4

```

* Last **global** timepoint: `r df.ecdc %>% pull(date_reported) %>% max()`
* Last **dutch** timepoint: `r df.ecdc %>% filter(geo_id == "NL") %>% pull(date_reported) %>% max()`

```{r}
f_plot_increase <- function(d) {
  d %>%
    pivot_longer(
      cols = c(new_cases, new_deaths),
      names_to = "variable",
      names_prefix = "new_",
      values_to = "value"
    ) %>%
    filter( value > 0 ) %>%
    ggplot(aes(x = date_reported, y= value, colour= variable )) +
    facet_wrap(~variable, scales="free_y") +
    geom_smooth() +
    geom_point() +
    scale_y_log10() +
    labs(
      x = "Date", y = p.label.log("new #")
    )
}

f_plot_cumulative <- function(d) {
  d %>%
    pivot_longer(
      cols = c(new_cases, new_deaths),
      names_to = "variable",
      names_prefix = "new_",
      values_to = "value"
    ) %>%
    group_by(variable) %>%
    mutate(
      cum_value = cumsum(value)
    ) %>%
    filter( cum_value > 0 ) %>%
    ggplot(aes(x = date_reported, y= cum_value, colour= variable )) +
    facet_wrap(~variable, scales="free_y") +
    geom_smooth() +
    geom_point() +
    scale_y_log10() +
    labs(
      x = "Date", y = p.label.log("cumalative #")
    )
}

f_plot_r_estimate <- function( d ) {
  
  d %>%
    ggplot(aes(x=t_end, y=`Mean(R)` )) +
    geom_point() +
    geom_line() +
    geom_ribbon(aes(ymin = `Quantile.0.025(R)`, ymax = `Quantile.0.975(R)`), alpha=0.1) +
    expand_limits(y=0) +
    labs(
      x = "Time (day)",
      y = "Estimated R"
    )
  
}
```

```{r}
df.ecdc %>%
  group_by(country) %>%
  summarise(
    last_report_date = max(date_reported)
  ) %>%
  ggplot(aes(last_report_date)) +
  geom_histogram()
```

## Global Situation

```{r}
df.ecdc %>%
  summarise_ecdc %>%
  f_plot_increase()
```

```{r}
df.ecdc %>%
  summarise_ecdc %>%
  f_plot_cumulative()
```

## European Situation

```{r}
df.ecdc %>%
  filter(geo_id %in% european) %>%
  summarise_ecdc %>%
  f_plot_increase()
```

```{r}
df.ecdc %>%
  filter(geo_id %in% european) %>%
  summarise_ecdc %>%
  f_plot_cumulative()
```

## Dutch Situation

```{r}
df.ecdc %>%
  filter(geo_id == "NL") %>%
  summarise_ecdc %>%
  f_plot_increase()
```

```{r}
df.ecdc %>%
  filter(geo_id == "NL") %>%
  summarise_ecdc %>%
  f_plot_cumulative()
```

## Estimate R

```{r}
f_estimate_r <- function( .d ) {
  v <- .d %>%
    arrange(date_reported) %>%
    filter(new_cases > 0) %>%
    pull(new_cases)
  
  result <- NA
  if (length(v) > 7) {
    
    result <- suppressMessages(estimate_R(
      v, method = "parametric_si", config = make_config(list(mean_si = si_mean, std_si = si_sd))
    ))
  }
      
}

f_extract_r <- function( .m ) {
  .m$R
}
```

```{r}
df.r <- df.ecdc %>%
  group_by(country, geo_id) %>%
  nest() %>%
  mutate(
    model = map(data, f_estimate_r),
    r_estimate = map(model, f_extract_r)
  ) %>%
  unnest(r_estimate)
```

### Global Situation

```{r}
df.ecdc %>%
  summarise_ecdc %>%
  f_estimate_r %>%
  f_extract_r %>%
  f_plot_r_estimate
```

### European Situation

```{r}
df.ecdc %>%
  filter(geo_id %in% european) %>%
  summarise_ecdc %>%
  f_estimate_r %>%
  f_extract_r %>%
  f_plot_r_estimate
```

### Dutch Situation

```{r}
df.r %>%
  filter(geo_id == "NL") %>% 
  f_plot_r_estimate
```